var bgp__config_8h =
[
    [ "AuthenticationKey", "d8/dbc/structAuthenticationKey.html", "d8/dbc/structAuthenticationKey" ],
    [ "AuthenticationData", "d1/df6/classAuthenticationData.html", "d1/df6/classAuthenticationData" ],
    [ "BgpFamilyAttributesConfig", "d7/d24/structBgpFamilyAttributesConfig.html", "d7/d24/structBgpFamilyAttributesConfig" ],
    [ "BgpFamilyAttributesConfigCompare", "d3/d7d/structBgpFamilyAttributesConfigCompare.html", "d3/d7d/structBgpFamilyAttributesConfigCompare" ],
    [ "BgpNeighborConfig", "d0/dbd/classBgpNeighborConfig.html", "d0/dbd/classBgpNeighborConfig" ],
    [ "OriginOverrideConfig", "db/df6/structBgpNeighborConfig_1_1OriginOverrideConfig.html", "db/df6/structBgpNeighborConfig_1_1OriginOverrideConfig" ],
    [ "AggregateRouteConfig", "db/db5/structAggregateRouteConfig.html", "db/db5/structAggregateRouteConfig" ],
    [ "ServiceChainConfig", "d8/d47/structServiceChainConfig.html", "d8/d47/structServiceChainConfig" ],
    [ "StaticRouteConfig", "d7/db3/structStaticRouteConfig.html", "d7/db3/structStaticRouteConfig" ],
    [ "PrefixMatchConfig", "dc/db8/structPrefixMatchConfig.html", "dc/db8/structPrefixMatchConfig" ],
    [ "RoutingPolicyMatchConfig", "db/d50/structRoutingPolicyMatchConfig.html", "db/d50/structRoutingPolicyMatchConfig" ],
    [ "ActionUpdate", "d9/da4/structActionUpdate.html", "d9/da4/structActionUpdate" ],
    [ "RoutingPolicyActionConfig", "d9/dab/structRoutingPolicyActionConfig.html", "d9/dab/structRoutingPolicyActionConfig" ],
    [ "RoutingPolicyTermConfig", "d5/d6c/structRoutingPolicyTermConfig.html", "d5/d6c/structRoutingPolicyTermConfig" ],
    [ "BgpRoutingPolicyConfig", "d4/dbb/classBgpRoutingPolicyConfig.html", "d4/dbb/classBgpRoutingPolicyConfig" ],
    [ "BgpInstanceConfig", "d6/ddf/classBgpInstanceConfig.html", "d6/ddf/classBgpInstanceConfig" ],
    [ "BgpProtocolConfig", "d6/d76/classBgpProtocolConfig.html", "d6/d76/classBgpProtocolConfig" ],
    [ "BgpGlobalSystemConfig", "d5/d70/classBgpGlobalSystemConfig.html", "d5/d70/classBgpGlobalSystemConfig" ],
    [ "BgpGlobalQosConfig", "d6/dd3/classBgpGlobalQosConfig.html", "d6/dd3/classBgpGlobalQosConfig" ],
    [ "BgpConfigManager", "da/d05/classBgpConfigManager.html", "da/d05/classBgpConfigManager" ],
    [ "Observers", "d7/d50/structBgpConfigManager_1_1Observers.html", "d7/d50/structBgpConfigManager_1_1Observers" ],
    [ "AsnList", "df/d8a/bgp__config_8h.html#ada29cf856a90ebb494abd9bfef6dd913", null ],
    [ "AuthenticationKeyChain", "df/d8a/bgp__config_8h.html#a7dc78a0d1f96cae224c3b12d86177b8d", null ],
    [ "CommunityList", "df/d8a/bgp__config_8h.html#a924af911e9938213fa5e145563c09d7b", null ],
    [ "PrefixMatchConfigList", "df/d8a/bgp__config_8h.html#ae21f84c4cfc55970f3a3385a7221db8e", null ],
    [ "ProtocolList", "df/d8a/bgp__config_8h.html#a2cacfdef63492b2d66e6291c74566a00", null ]
];